


/*Generated by the BSD Licensed BarelyMVC ViewGenerator T4 file*/
using System.Text;
using System.Collections.Generic;
using System.Web;
using System.IO;
using System;
using Earlz.BarelyMVC.ViewEngine;
using Earlz.BarelyMVC;

        //custom using statements for your views go here:
        
    

//