

/*Generated by the BSD Licensed BarelyMVC ViewGenerator T4 file*/
using System.Text;
using System.Collections.Generic;
using System;
using Earlz.BarelyMVC.ViewEngine;
using Earlz.BarelyMVC.ViewEngine.Helpers;

		//custom using statements for your views go here:
		
	
//Internal base class
namespace Earlz.BarelyMVC.ViewEngine
{
	public interface IBarelyView
	{
		string RenderView();
	}
}
//internal empty namespace declaration
namespace Earlz.BarelyMVC.ViewEngine.Helpers{}

namespace Earlz.BarelyMVC.ViewEngine.Internal{
	public abstract class BarelyViewDummy : Earlz.BarelyMVC.ViewEngine.IBarelyView{ /*This is needed because we have to make a function overridden. */
		public virtual string RenderView(){throw new NotImplementedException();}
		public override string ToString(){return RenderView();}
	}
}



