

/*Generated by the BSD Licensed BarelyMVC ViewGenerator T4 file*/
using System.Text;
using System.Collections.Generic;
using System.Web;
using System.IO;
using System;
using Earlz.BarelyMVC.ViewEngine;

		//custom using statements for your views go here:
		
		using System.Linq; //required if unit testing the ViewGenerator. (also doesn't hurt to be there anyway)
	

//